// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	context "context"

	health "github.com/ava-labs/avalanchego/api/health"
	mock "github.com/stretchr/testify/mock"

	rpc "github.com/ava-labs/avalanchego/utils/rpc"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Health provides a mock function with given fields: ctx, tags, options
func (_m *Client) Health(ctx context.Context, tags []string, options ...rpc.Option) (*health.APIReply, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, tags)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *health.APIReply
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, ...rpc.Option) (*health.APIReply, error)); ok {
		return rf(ctx, tags, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, ...rpc.Option) *health.APIReply); ok {
		r0 = rf(ctx, tags, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*health.APIReply)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, ...rpc.Option) error); ok {
		r1 = rf(ctx, tags, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Liveness provides a mock function with given fields: ctx, tags, options
func (_m *Client) Liveness(ctx context.Context, tags []string, options ...rpc.Option) (*health.APIReply, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, tags)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *health.APIReply
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, ...rpc.Option) (*health.APIReply, error)); ok {
		return rf(ctx, tags, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, ...rpc.Option) *health.APIReply); ok {
		r0 = rf(ctx, tags, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*health.APIReply)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, ...rpc.Option) error); ok {
		r1 = rf(ctx, tags, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Readiness provides a mock function with given fields: ctx, tags, options
func (_m *Client) Readiness(ctx context.Context, tags []string, options ...rpc.Option) (*health.APIReply, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, tags)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *health.APIReply
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, ...rpc.Option) (*health.APIReply, error)); ok {
		return rf(ctx, tags, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, ...rpc.Option) *health.APIReply); ok {
		r0 = rf(ctx, tags, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*health.APIReply)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, ...rpc.Option) error); ok {
		r1 = rf(ctx, tags, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t mockConstructorTestingTNewClient) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
