# ref. https://golangci-lint.run/usage/configuration/
run:
  timeout: 5m
  tests: false
  skip-dirs:
    - api/mocks
    - k8s/mocks
    - local/mocks
    - rpcpb
  go: "1.17"

linters:
  disable:
    - typecheck
