# ref. https://goreleaser.com/customization/build/
builds:
  - id: avalanche-network-runner
    main: ./main.go
    binary: avalanche-network-runner
    flags:
      - -v
    ldflags:
      - -X 'github.com/ava-labs/avalanche-network-runner/cmd.Version={{.Version}}'
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: freebsd
        goarch: 386
    env:
      - CGO_CFLAGS=-O -D__BLST_PORTABLE__

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: ava-labs
    name: avalanche-network-runner
