---
apiVersion: v1
kind: Pod 
metadata:
  name: k8s-netrunner 
  namespace: ci-avalanchego 
spec:
  containers:
  - name: k8s-netrunner 
    image: k8s-netrunner:alpha
    imagePullPolicy: IfNotPresent 
  restartPolicy: Never
  serviceAccountName:  k8s-netrunner
