// Code generated by mockery v2.51.0. DO NOT EDIT.

package mocks

import (
	logging "github.com/ava-labs/avalanchego/utils/logging"
	mock "github.com/stretchr/testify/mock"
)

// ColorPicker is an autogenerated mock type for the ColorPicker type
type ColorPicker struct {
	mock.Mock
}

// NextColor provides a mock function with no fields
func (_m *ColorPicker) NextColor() logging.Color {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NextColor")
	}

	var r0 logging.Color
	if rf, ok := ret.Get(0).(func() logging.Color); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(logging.Color)
	}

	return r0
}

// NewColorPicker creates a new instance of ColorPicker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewColorPicker(t interface {
	mock.TestingT
	Cleanup(func())
}) *ColorPicker {
	mock := &ColorPicker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
