// Code generated by mockery v2.51.0. DO NOT EDIT.

package mocks

import (
	client "github.com/ava-labs/avalanche-network-runner/client"
	mock "github.com/stretchr/testify/mock"
)

// OpOption is an autogenerated mock type for the OpOption type
type OpOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *OpOption) Execute(_a0 *client.Op) {
	_m.Called(_a0)
}

// NewOpOption creates a new instance of OpOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOpOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *OpOption {
	mock := &OpOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
