// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DnsReachableChecker is an autogenerated mock type for the dnsReachableChecker type
type DnsReachableChecker struct {
	mock.Mock
}

// Reachable provides a mock function with given fields: ctx, url
func (_m *DnsReachableChecker) Reachable(ctx context.Context, url string) bool {
	ret := _m.Called(ctx, url)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
