// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DNSCheck is an autogenerated mock type for the DNSCheck type
type DNSCheck struct {
	mock.Mock
}

// Reachable provides a mock function with given fields: url
func (_m *DNSCheck) Reachable(url string) error {
	ret := _m.Called(url)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
