name: Build + test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint_test:
    name: Lint tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '~1.21.7'
          check-latest: true
      - name: Run static analysis tests
        shell: bash
        run: scripts/lint.sh
  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '~1.21.7'
      - run: go test -v -timeout 10m -race ./...
        env:
          CGO_CFLAGS: "-O -D__BLST_PORTABLE__" # Set the CGO flags to use the portable version of BLST
  e2e_test:
    name: e2e tests
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-20.04, macos-12]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '~1.21.7'
      - name: Run e2e tests
        shell: bash
        run: scripts/tests.e2e.sh
      - name: Set ubuntu tmpdir into actions env
        if: always() && startsWith(matrix.os, 'ubuntu')
        run: echo "ANR_TMPDIR=/tmp/" >> $GITHUB_ENV
      - name: Set macos tmpdir into actions env
        if: always() && startsWith(matrix.os, 'macos')
        run: echo "ANR_TMPDIR=$TMPDIR" >> $GITHUB_ENV
      - name: "Upload Artifact"
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: anr-logs-${{ matrix.os }}
          path: |
            ${{ env.ANR_TMPDIR }}/network-runner-root-data*
          retention-days: 5
