name: run-fivenodenetwork

on: 
 push:
 pull_request:
   branches: 
     - master

jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with: 
          go-version: '1.17.3' # The Go version to use.
      - run: go version
    
      - name: Run five-nodes-network 
        run: .github/workflows/fivenodenetwork-ci.sh 
